# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='character',
        ),
        migrations.AlterField(
            model_name='character',
            name='page',
            field=models.TextField(),
        ),
    ]
