# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0002_auto_20171102_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gotsv2.Gender'),
            preserve_default=False,
        ),
    ]
