# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0003_character_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gotsv2.Gender'),
        ),
    ]
