# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0004_auto_20171102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='titles',
            field=models.TextField(default=''),
        ),
    ]
