# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0005_character_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='titles',
            field=models.TextField(default=None, null=True),
        ),
    ]
