# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0006_auto_20171118_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotsv2.Gender'),
        ),
    ]
