# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotsv2', '0007_auto_20171210_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='title_strings',
            field=models.TextField(default=None, null=True),
        ),
    ]
